class Effect: "Minecraft Effect"

speed: Effect
slowness: Effect
haste: Effect
mining_fatigue: Effect
strength: Effect
instant_health: Effect
instant_damage: Effect
jump_boost: Effect
nausea: Effect
regeneration: Effect
resistance: Effect
fire_resistance: Effect
water_breathing: Effect
invisibility: Effect
blindness: Effect
night_vision: Effect
hunger: Effect
weakness: Effect
poison: Effect
wither: Effect
health_boost: Effect
absorption: Effect
saturation: Effect
glowing: Effect
levitation: Effect
luck: Effect
unluck: Effect
slow_falling: Effect
conduit_power: Effect
dolphins_grace: Effect
bad_omen: Effect
hero_of_the_village: Effect
darkness: Effect
trial_omen: Effect
raid_omen: Effect
wind_charged: Effect
weaving: Effect
oozing: Effect
infested: Effect