class Block:
    str

acacia_button: Block
acacia_door: Block
acacia_fence: Block
acacia_fence_gate: Block
acacia_leaves: Block
acacia_log: Block
acacia_planks: Block
acacia_pressure_plate: Block
acacia_sapling: Block
acacia_sign: Block
acacia_slab: Block
acacia_stairs: Block
acacia_trapdoor: Block
acacia_wall_sign: Block
acacia_wood: Block
activator_rail: Block
air: Block
allium: Block
amethyst_block: Block
amethyst_cluster: Block
ancient_debris: Block
andesite: Block
andesite_slab: Block
andesite_stairs: Block
andesite_wall: Block
anvil: Block
attached_melon_stem: Block
attached_pumpkin_stem: Block
azalea: Block
azalea_leaves: Block
azure_bluet: Block
bamboo: Block
bamboo_sapling: Block
barrel: Block
barrier: Block
basalt: Block
beacon: Block
bedrock: Block
bee_nest: Block
beehive: Block
beetroots: Block
bell: Block
big_dripleaf: Block
big_dripleaf_stem: Block
birch_button: Block
birch_door: Block
birch_fence: Block
birch_fence_gate: Block
birch_leaves: Block
birch_log: Block
birch_planks: Block
birch_pressure_plate: Block
birch_sapling: Block
birch_sign: Block
birch_slab: Block
birch_stairs: Block
birch_trapdoor: Block
birch_wall_sign: Block
birch_wood: Block
black_banner: Block
black_bed: Block
black_candle: Block
black_candle_cake: Block
black_carpet: Block
black_concrete: Block
black_concrete_powder: Block
black_glazed_terracotta: Block
black_shulker_box: Block
black_stained_glass: Block
black_stained_glass_pane: Block
black_terracotta: Block
black_wall_banner: Block
black_wool: Block
blackstone: Block
blackstone_slab: Block
blackstone_stairs: Block
blackstone_wall: Block
blast_furnace: Block
blue_banner: Block
blue_bed: Block
blue_candle: Block
blue_candle_cake: Block
blue_carpet: Block
blue_concrete: Block
blue_concrete_powder: Block
blue_glazed_terracotta: Block
blue_ice: Block
blue_orchid: Block
blue_shulker_box: Block
blue_stained_glass: Block
blue_stained_glass_pane: Block
blue_terracotta: Block
blue_wall_banner: Block
blue_wool: Block
bone_block: Block
bookshelf: Block
brain_coral: Block
brain_coral_block: Block
brain_coral_fan: Block
brain_coral_wall_fan: Block
brewing_stand: Block
brick_slab: Block
brick_stairs: Block
brick_wall: Block
bricks: Block
brown_banner: Block
brown_bed: Block
brown_candle: Block
brown_candle_cake: Block
brown_carpet: Block
brown_concrete: Block
brown_concrete_powder: Block
brown_glazed_terracotta: Block
brown_mushroom: Block
brown_mushroom_block: Block
brown_shulker_box: Block
brown_stained_glass: Block
brown_stained_glass_pane: Block
brown_terracotta: Block
brown_wall_banner: Block
brown_wool: Block
bubble_column: Block
bubble_coral: Block
bubble_coral_block: Block
bubble_coral_fan: Block
bubble_coral_wall_fan: Block
budding_amethyst: Block
cactus: Block
cake: Block
calcite: Block
campfire: Block
candle: Block
candle_cake: Block
carrots: Block
cartography_table: Block
carved_pumpkin: Block
cauldron: Block
cave_air: Block
cave_vines: Block
cave_vines_plant: Block
chain: Block
chain_command_block: Block
chest: Block
chipped_anvil: Block
chiseled_deepslate: Block
chiseled_nether_bricks: Block
chiseled_polished_blackstone: Block
chiseled_quartz_block: Block
chiseled_red_sandstone: Block
chiseled_sandstone: Block
chiseled_stone_bricks: Block
chorus_flower: Block
chorus_plant: Block
clay: Block
coal_block: Block
coal_ore: Block
coarse_dirt: Block
cobbled_deepslate: Block
cobbled_deepslate_slab: Block
cobbled_deepslate_stairs: Block
cobbled_deepslate_wall: Block
cobblestone: Block
cobblestone_slab: Block
cobblestone_stairs: Block
cobblestone_wall: Block
cobweb: Block
cocoa: Block
command_block: Block
comparator: Block
composter: Block
conduit: Block
copper_block: Block
copper_ore: Block
cornflower: Block
cracked_deepslate_bricks: Block
cracked_deepslate_tiles: Block
cracked_nether_bricks: Block
cracked_polished_blackstone_bricks: Block
cracked_stone_bricks: Block
crafting_table: Block
creeper_head: Block
creeper_wall_head: Block
crimson_button: Block
crimson_door: Block
crimson_fence: Block
crimson_fence_gate: Block
crimson_fungus: Block
crimson_hyphae: Block
crimson_nylium: Block
crimson_planks: Block
crimson_pressure_plate: Block
crimson_roots: Block
crimson_sign: Block
crimson_slab: Block
crimson_stairs: Block
crimson_stem: Block
crimson_trapdoor: Block
crimson_wall_sign: Block
crying_obsidian: Block
cut_copper: Block
cut_copper_slab: Block
cut_copper_stairs: Block
cut_red_sandstone: Block
cut_red_sandstone_slab: Block
cut_sandstone: Block
cut_sandstone_slab: Block
cyan_banner: Block
cyan_bed: Block
cyan_candle: Block
cyan_candle_cake: Block
cyan_carpet: Block
cyan_concrete: Block
cyan_concrete_powder: Block
cyan_glazed_terracotta: Block
cyan_shulker_box: Block
cyan_stained_glass: Block
cyan_stained_glass_pane: Block
cyan_terracotta: Block
cyan_wall_banner: Block
cyan_wool: Block
damaged_anvil: Block
dandelion: Block
dark_oak_button: Block
dark_oak_door: Block
dark_oak_fence: Block
dark_oak_fence_gate: Block
dark_oak_leaves: Block
dark_oak_log: Block
dark_oak_planks: Block
dark_oak_pressure_plate: Block
dark_oak_sapling: Block
dark_oak_sign: Block
dark_oak_slab: Block
dark_oak_stairs: Block
dark_oak_trapdoor: Block
dark_oak_wall_sign: Block
dark_oak_wood: Block
dark_prismarine: Block
dark_prismarine_slab: Block
dark_prismarine_stairs: Block
daylight_detector: Block
dead_brain_coral: Block
dead_brain_coral_block: Block
dead_brain_coral_fan: Block
dead_brain_coral_wall_fan: Block
dead_bubble_coral: Block
dead_bubble_coral_block: Block
dead_bubble_coral_fan: Block
dead_bubble_coral_wall_fan: Block
dead_bush: Block
dead_fire_coral: Block
dead_fire_coral_block: Block
dead_fire_coral_fan: Block
dead_fire_coral_wall_fan: Block
dead_horn_coral: Block
dead_horn_coral_block: Block
dead_horn_coral_fan: Block
dead_horn_coral_wall_fan: Block
dead_tube_coral: Block
dead_tube_coral_block: Block
dead_tube_coral_fan: Block
dead_tube_coral_wall_fan: Block
deepslate: Block
deepslate_brick_slab: Block
deepslate_brick_stairs: Block
deepslate_brick_wall: Block
deepslate_bricks: Block
deepslate_coal_ore: Block
deepslate_copper_ore: Block
deepslate_diamond_ore: Block
deepslate_emerald_ore: Block
deepslate_gold_ore: Block
deepslate_iron_ore: Block
deepslate_lapis_ore: Block
deepslate_redstone_ore: Block
deepslate_tile_slab: Block
deepslate_tile_stairs: Block
deepslate_tile_wall: Block
deepslate_tiles: Block
detector_rail: Block
diamond_block: Block
diamond_ore: Block
diorite: Block
diorite_slab: Block
diorite_stairs: Block
diorite_wall: Block
dirt: Block
dirt_path: Block
dispenser: Block
dragon_egg: Block
dragon_head: Block
dragon_wall_head: Block
dried_kelp_block: Block
dripstone_block: Block
dropper: Block
emerald_block: Block
emerald_ore: Block
enchanting_table: Block
end_gateway: Block
end_portal: Block
end_portal_frame: Block
end_rod: Block
end_stone: Block
end_stone_brick_slab: Block
end_stone_brick_stairs: Block
end_stone_brick_wall: Block
end_stone_bricks: Block
ender_chest: Block
exposed_copper: Block
exposed_cut_copper: Block
exposed_cut_copper_slab: Block
exposed_cut_copper_stairs: Block
farmland: Block
fern: Block
fire: Block
fire_coral: Block
fire_coral_block: Block
fire_coral_fan: Block
fire_coral_wall_fan: Block
fletching_table: Block
flower_pot: Block
flowering_azalea: Block
flowering_azalea_leaves: Block
frogspawn: Block
frosted_ice: Block
furnace: Block
gilded_blackstone: Block
glass: Block
glass_pane: Block
glow_lichen: Block
glowstone: Block
gold_block: Block
gold_ore: Block
granite: Block
granite_slab: Block
granite_stairs: Block
granite_wall: Block
grass: Block
grass_block: Block
gravel: Block
gray_banner: Block
gray_bed: Block
gray_candle: Block
gray_candle_cake: Block
gray_carpet: Block
gray_concrete: Block
gray_concrete_powder: Block
gray_glazed_terracotta: Block
gray_shulker_box: Block
gray_stained_glass: Block
gray_stained_glass_pane: Block
gray_terracotta: Block
gray_wall_banner: Block
gray_wool: Block
green_banner: Block
green_bed: Block
green_candle: Block
green_candle_cake: Block
green_carpet: Block
green_concrete: Block
green_concrete_powder: Block
green_glazed_terracotta: Block
green_shulker_box: Block
green_stained_glass: Block
green_stained_glass_pane: Block
green_terracotta: Block
green_wall_banner: Block
green_wool: Block
grindstone: Block
hanging_roots: Block
hay_block: Block
heavy_weighted_pressure_plate: Block
honey_block: Block
honeycomb_block: Block
hopper: Block
horn_coral: Block
horn_coral_block: Block
horn_coral_fan: Block
horn_coral_wall_fan: Block
ice: Block
infested_chiseled_stone_bricks: Block
infested_cobblestone: Block
infested_cracked_stone_bricks: Block
infested_deepslate: Block
infested_mossy_stone_bricks: Block
infested_stone: Block
infested_stone_bricks: Block
iron_bars: Block
iron_block: Block
iron_door: Block
iron_ore: Block
iron_trapdoor: Block
jack_o_lantern: Block
jigsaw: Block
jukebox: Block
jungle_button: Block
jungle_door: Block
jungle_fence: Block
jungle_fence_gate: Block
jungle_leaves: Block
jungle_log: Block
jungle_planks: Block
jungle_pressure_plate: Block
jungle_sapling: Block
jungle_sign: Block
jungle_slab: Block
jungle_stairs: Block
jungle_trapdoor: Block
jungle_wall_sign: Block
jungle_wood: Block
kelp: Block
kelp_plant: Block
ladder: Block
lantern: Block
lapis_block: Block
lapis_ore: Block
large_amethyst_bud: Block
large_fern: Block
lava: Block
lava_cauldron: Block
lectern: Block
lever: Block
light: Block
light_blue_banner: Block
light_blue_bed: Block
light_blue_candle: Block
light_blue_candle_cake: Block
light_blue_carpet: Block
light_blue_concrete: Block
light_blue_concrete_powder: Block
light_blue_glazed_terracotta: Block
light_blue_shulker_box: Block
light_blue_stained_glass: Block
light_blue_stained_glass_pane: Block
light_blue_terracotta: Block
light_blue_wall_banner: Block
light_blue_wool: Block
light_gray_banner: Block
light_gray_bed: Block
light_gray_candle: Block
light_gray_candle_cake: Block
light_gray_carpet: Block
light_gray_concrete: Block
light_gray_concrete_powder: Block
light_gray_glazed_terracotta: Block
light_gray_shulker_box: Block
light_gray_stained_glass: Block
light_gray_stained_glass_pane: Block
light_gray_terracotta: Block
light_gray_wall_banner: Block
light_gray_wool: Block
light_weighted_pressure_plate: Block
lightning_rod: Block
lilac: Block
lily_of_the_valley: Block
lily_pad: Block
lime_banner: Block
lime_bed: Block
lime_candle: Block
lime_candle_cake: Block
lime_carpet: Block
lime_concrete: Block
lime_concrete_powder: Block
lime_glazed_terracotta: Block
lime_shulker_box: Block
lime_stained_glass: Block
lime_stained_glass_pane: Block
lime_terracotta: Block
lime_wall_banner: Block
lime_wool: Block
lodestone: Block
loom: Block
magenta_banner: Block
magenta_bed: Block
magenta_candle: Block
magenta_candle_cake: Block
magenta_carpet: Block
magenta_concrete: Block
magenta_concrete_powder: Block
magenta_glazed_terracotta: Block
magenta_shulker_box: Block
magenta_stained_glass: Block
magenta_stained_glass_pane: Block
magenta_terracotta: Block
magenta_wall_banner: Block
magenta_wool: Block
magma_block: Block
mangrove_button: Block
mangrove_door: Block
mangrove_fence: Block
mangrove_fence_gate: Block
mangrove_leaves: Block
mangrove_log: Block
mangrove_planks: Block
mangrove_pressure_plate: Block
mangrove_propagule: Block
mangrove_roots: Block
mangrove_sign: Block
mangrove_slab: Block
mangrove_stairs: Block
mangrove_trapdoor: Block
mangrove_wall_sign: Block
mangrove_wood: Block
medium_amethyst_bud: Block
melon: Block
melon_stem: Block
moss_block: Block
moss_carpet: Block
mossy_cobblestone: Block
mossy_cobblestone_slab: Block
mossy_cobblestone_stairs: Block
mossy_cobblestone_wall: Block
mossy_stone_brick_slab: Block
mossy_stone_brick_stairs: Block
mossy_stone_brick_wall: Block
mossy_stone_bricks: Block
moving_piston: Block
mud: Block
mud_brick_slab: Block
mud_brick_stairs: Block
mud_brick_wall: Block
mud_bricks: Block
muddy_mangrove_roots: Block
mushroom_stem: Block
mycelium: Block
nether_brick_fence: Block
nether_brick_slab: Block
nether_brick_stairs: Block
nether_brick_wall: Block
nether_bricks: Block
nether_gold_ore: Block
nether_portal: Block
nether_quartz_ore: Block
nether_sprouts: Block
nether_wart: Block
nether_wart_block: Block
netherite_block: Block
netherrack: Block
note_block: Block
oak_button: Block
oak_door: Block
oak_fence: Block
oak_fence_gate: Block
oak_leaves: Block
oak_log: Block
oak_planks: Block
oak_pressure_plate: Block
oak_sapling: Block
oak_sign: Block
oak_slab: Block
oak_stairs: Block
oak_trapdoor: Block
oak_wall_sign: Block
oak_wood: Block
observer: Block
obsidian: Block
ochre_froglight: Block
orange_banner: Block
orange_bed: Block
orange_candle: Block
orange_candle_cake: Block
orange_carpet: Block
orange_concrete: Block
orange_concrete_powder: Block
orange_glazed_terracotta: Block
orange_shulker_box: Block
orange_stained_glass: Block
orange_stained_glass_pane: Block
orange_terracotta: Block
orange_tulip: Block
orange_wall_banner: Block
orange_wool: Block
oxeye_daisy: Block
oxidized_copper: Block
oxidized_cut_copper: Block
oxidized_cut_copper_slab: Block
oxidized_cut_copper_stairs: Block
packed_ice: Block
packed_mud: Block
pearlescent_froglight: Block
peony: Block
petrified_oak_slab: Block
pink_banner: Block
pink_bed: Block
pink_candle: Block
pink_candle_cake: Block
pink_carpet: Block
pink_concrete: Block
pink_concrete_powder: Block
pink_glazed_terracotta: Block
pink_shulker_box: Block
pink_stained_glass: Block
pink_stained_glass_pane: Block
pink_terracotta: Block
pink_tulip: Block
pink_wall_banner: Block
pink_wool: Block
piston: Block
piston_head: Block
player_head: Block
player_wall_head: Block
podzol: Block
pointed_dripstone: Block
polished_andesite: Block
polished_andesite_slab: Block
polished_andesite_stairs: Block
polished_basalt: Block
polished_blackstone: Block
polished_blackstone_brick_slab: Block
polished_blackstone_brick_stairs: Block
polished_blackstone_brick_wall: Block
polished_blackstone_bricks: Block
polished_blackstone_button: Block
polished_blackstone_pressure_plate: Block
polished_blackstone_slab: Block
polished_blackstone_stairs: Block
polished_blackstone_wall: Block
polished_deepslate: Block
polished_deepslate_slab: Block
polished_deepslate_stairs: Block
polished_deepslate_wall: Block
polished_diorite: Block
polished_diorite_slab: Block
polished_diorite_stairs: Block
polished_granite: Block
polished_granite_slab: Block
polished_granite_stairs: Block
poppy: Block
potatoes: Block
potted_acacia_sapling: Block
potted_allium: Block
potted_azalea_bush: Block
potted_azure_bluet: Block
potted_bamboo: Block
potted_birch_sapling: Block
potted_blue_orchid: Block
potted_brown_mushroom: Block
potted_cactus: Block
potted_cornflower: Block
potted_crimson_fungus: Block
potted_crimson_roots: Block
potted_dandelion: Block
potted_dark_oak_sapling: Block
potted_dead_bush: Block
potted_fern: Block
potted_flowering_azalea_bush: Block
potted_jungle_sapling: Block
potted_lily_of_the_valley: Block
potted_mangrove_propagule: Block
potted_oak_sapling: Block
potted_orange_tulip: Block
potted_oxeye_daisy: Block
potted_pink_tulip: Block
potted_poppy: Block
potted_red_mushroom: Block
potted_red_tulip: Block
potted_spruce_sapling: Block
potted_warped_fungus: Block
potted_warped_roots: Block
potted_white_tulip: Block
potted_wither_rose: Block
powder_snow: Block
powder_snow_cauldron: Block
powered_rail: Block
prismarine: Block
prismarine_brick_slab: Block
prismarine_brick_stairs: Block
prismarine_bricks: Block
prismarine_slab: Block
prismarine_stairs: Block
prismarine_wall: Block
pumpkin: Block
pumpkin_stem: Block
purple_banner: Block
purple_bed: Block
purple_candle: Block
purple_candle_cake: Block
purple_carpet: Block
purple_concrete: Block
purple_concrete_powder: Block
purple_glazed_terracotta: Block
purple_shulker_box: Block
purple_stained_glass: Block
purple_stained_glass_pane: Block
purple_terracotta: Block
purple_wall_banner: Block
purple_wool: Block
purpur_block: Block
purpur_pillar: Block
purpur_slab: Block
purpur_stairs: Block
quartz_block: Block
quartz_bricks: Block
quartz_pillar: Block
quartz_slab: Block
quartz_stairs: Block
rail: Block
raw_copper_block: Block
raw_gold_block: Block
raw_iron_block: Block
red_banner: Block
red_bed: Block
red_candle: Block
red_candle_cake: Block
red_carpet: Block
red_concrete: Block
red_concrete_powder: Block
red_glazed_terracotta: Block
red_mushroom: Block
red_mushroom_block: Block
red_nether_brick_slab: Block
red_nether_brick_stairs: Block
red_nether_brick_wall: Block
red_nether_bricks: Block
red_sand: Block
red_sandstone: Block
red_sandstone_slab: Block
red_sandstone_stairs: Block
red_sandstone_wall: Block
red_shulker_box: Block
red_stained_glass: Block
red_stained_glass_pane: Block
red_terracotta: Block
red_tulip: Block
red_wall_banner: Block
red_wool: Block
redstone_block: Block
redstone_lamp: Block
redstone_ore: Block
redstone_torch: Block
redstone_wall_torch: Block
redstone_wire: Block
reinforced_deepslate: Block
repeater: Block
repeating_command_block: Block
respawn_anchor: Block
rooted_dirt: Block
rose_bush: Block
sand: Block
sandstone: Block
sandstone_slab: Block
sandstone_stairs: Block
sandstone_wall: Block
scaffolding: Block
sculk: Block
sculk_catalyst: Block
sculk_sensor: Block
sculk_shrieker: Block
sculk_vein: Block
sea_lantern: Block
sea_pickle: Block
seagrass: Block
shroomlight: Block
shulker_box: Block
skeleton_skull: Block
skeleton_wall_skull: Block
slime_block: Block
small_amethyst_bud: Block
small_dripleaf: Block
smithing_table: Block
smoker: Block
smooth_basalt: Block
smooth_quartz: Block
smooth_quartz_slab: Block
smooth_quartz_stairs: Block
smooth_red_sandstone: Block
smooth_red_sandstone_slab: Block
smooth_red_sandstone_stairs: Block
smooth_sandstone: Block
smooth_sandstone_slab: Block
smooth_sandstone_stairs: Block
smooth_stone: Block
smooth_stone_slab: Block
snow: Block
snow_block: Block
soul_campfire: Block
soul_fire: Block
soul_lantern: Block
soul_sand: Block
soul_soil: Block
soul_torch: Block
soul_wall_torch: Block
spawner: Block
sponge: Block
spore_blossom: Block
spruce_button: Block
spruce_door: Block
spruce_fence: Block
spruce_fence_gate: Block
spruce_leaves: Block
spruce_log: Block
spruce_planks: Block
spruce_pressure_plate: Block
spruce_sapling: Block
spruce_sign: Block
spruce_slab: Block
spruce_stairs: Block
spruce_trapdoor: Block
spruce_wall_sign: Block
spruce_wood: Block
sticky_piston: Block
stone: Block
stone_brick_slab: Block
stone_brick_stairs: Block
stone_brick_wall: Block
stone_bricks: Block
stone_button: Block
stone_pressure_plate: Block
stone_slab: Block
stone_stairs: Block
stonecutter: Block
stripped_acacia_log: Block
stripped_acacia_wood: Block
stripped_birch_log: Block
stripped_birch_wood: Block
stripped_crimson_hyphae: Block
stripped_crimson_stem: Block
stripped_dark_oak_log: Block
stripped_dark_oak_wood: Block
stripped_jungle_log: Block
stripped_jungle_wood: Block
stripped_mangrove_log: Block
stripped_mangrove_wood: Block
stripped_oak_log: Block
stripped_oak_wood: Block
stripped_spruce_log: Block
stripped_spruce_wood: Block
stripped_warped_hyphae: Block
stripped_warped_stem: Block
structure_block: Block
structure_void: Block
sugar_cane: Block
sunflower: Block
sweet_berry_bush: Block
tall_grass: Block
tall_seagrass: Block
target: Block
terracotta: Block
tinted_glass: Block
tnt: Block
torch: Block
trapped_chest: Block
tripwire: Block
tripwire_hook: Block
tube_coral: Block
tube_coral_block: Block
tube_coral_fan: Block
tube_coral_wall_fan: Block
tuff: Block
turtle_egg: Block
twisting_vines: Block
twisting_vines_plant: Block
verdant_froglight: Block
vine: Block
void_air: Block
wall_torch: Block
warped_button: Block
warped_door: Block
warped_fence: Block
warped_fence_gate: Block
warped_fungus: Block
warped_hyphae: Block
warped_nylium: Block
warped_planks: Block
warped_pressure_plate: Block
warped_roots: Block
warped_sign: Block
warped_slab: Block
warped_stairs: Block
warped_stem: Block
warped_trapdoor: Block
warped_wall_sign: Block
warped_wart_block: Block
water: Block
water_cauldron: Block
waxed_copper_block: Block
waxed_cut_copper: Block
waxed_cut_copper_slab: Block
waxed_cut_copper_stairs: Block
waxed_exposed_copper: Block
waxed_exposed_cut_copper: Block
waxed_exposed_cut_copper_slab: Block
waxed_exposed_cut_copper_stairs: Block
waxed_oxidized_copper: Block
waxed_oxidized_cut_copper: Block
waxed_oxidized_cut_copper_slab: Block
waxed_oxidized_cut_copper_stairs: Block
waxed_weathered_copper: Block
waxed_weathered_cut_copper: Block
waxed_weathered_cut_copper_slab: Block
waxed_weathered_cut_copper_stairs: Block
weathered_copper: Block
weathered_cut_copper: Block
weathered_cut_copper_slab: Block
weathered_cut_copper_stairs: Block
weeping_vines: Block
weeping_vines_plant: Block
wet_sponge: Block
wheat: Block
white_banner: Block
white_bed: Block
white_candle: Block
white_candle_cake: Block
white_carpet: Block
white_concrete: Block
white_concrete_powder: Block
white_glazed_terracotta: Block
white_shulker_box: Block
white_stained_glass: Block
white_stained_glass_pane: Block
white_terracotta: Block
white_tulip: Block
white_wall_banner: Block
white_wool: Block
wither_rose: Block
wither_skeleton_skull: Block
wither_skeleton_wall_skull: Block
yellow_banner: Block
yellow_bed: Block
yellow_candle: Block
yellow_candle_cake: Block
yellow_carpet: Block
yellow_concrete: Block
yellow_concrete_powder: Block
yellow_glazed_terracotta: Block
yellow_shulker_box: Block
yellow_stained_glass: Block
yellow_stained_glass_pane: Block
yellow_terracotta: Block
yellow_wall_banner: Block
yellow_wool: Block
zombie_head: Block
zombie_wall_head: Block