class Entity:
    str

allay: Entity
area_effect_cloud: Entity
armadillo: Entity
armor_stand: Entity
arrow: Entity
axolotl: Entity
bat: Entity
bee: Entity
blaze: Entity
block_display: Entity
boat: Entity
chest_boat: Entity
bogged: Entity
breeze: Entity
camel: Entity
cat: Entity
cave_spider: Entity
chicken: Entity
cod: Entity
cow: Entity
creeper: Entity
dolphin: Entity
donkey: Entity
dragon_fireball: Entity
drowned: Entity
elder_guardian: Entity
end_crystal: Entity
ender_dragon: Entity
enderman: Entity
endermite: Entity
evoker: Entity
evoker_fangs: Entity
experience_orb: Entity
eye_of_ender: Entity
falling_block: Entity
fireball: Entity
firework_rocket: Entity
fishing_bobber: Entity
fox: Entity
frog: Entity
ghast: Entity
giant: Entity
glow_item_frame: Entity
glow_squid: Entity
goat: Entity
guardian: Entity
hoglin: Entity
horse: Entity
husk: Entity
illusioner: Entity
interaction: Entity
iron_golem: Entity
item: Entity
item_display: Entity
item_frame: Entity
leash_knot: Entity
lightning_bolt: Entity
llama: Entity
llama_spit: Entity
magma_cube: Entity
marker: Entity
minecart: Entity
chest_minecart: Entity
command_block_minecart: Entity
furnace_minecart: Entity
hopper_minecart: Entity
spawner_minecart: Entity
tnt_minecart: Entity
mooshroom: Entity
mule: Entity
ocelot: Entity
ominous_item_spawner: Entity
painting: Entity
panda: Entity
parrot: Entity
phantom: Entity
pig: Entity
piglin: Entity
piglin_brute: Entity
pillager: Entity
player: Entity
polar_bear: Entity
potion: Entity
tnt: Entity
pufferfish: Entity
rabbit: Entity
ravager: Entity
salmon: Entity
sheep: Entity
shulker: Entity
shulker_bullet: Entity
silverfish: Entity
skeleton: Entity
skeleton_horse: Entity
slime: Entity
small_fireball: Entity
sniffer: Entity
snow_golem: Entity
snowball: Entity
spectral_arrow: Entity
spider: Entity
squid: Entity
stray: Entity
strider: Entity
tadpole: Entity
text_display: Entity
experience_bottle: Entity
egg: Entity
ender_pearl: Entity
trader_llama: Entity
trident: Entity
tropical_fish: Entity
turtle: Entity
vex: Entity
villager: Entity
vindicator: Entity
wandering_trader: Entity
warden: Entity
wind_charge: Entity
witch: Entity
wither: Entity
wither_skeleton: Entity
wither_skull: Entity
wolf: Entity
zoglin: Entity
zombie: Entity
zombie_horse: Entity
zombie_villager: Entity
zombified_piglin: Entity