class Item:
    str

stone: Item
granite: Item
polished_granite: Item
diorite: Item
polished_diorite: Item
andesite: Item
polished_andesite: Item
deepslate: Item
cobbled_deepslate: Item
polished_deepslate: Item
calcite: Item
tuff: Item
dripstone_block: Item
grass_block: Item
dirt: Item
coarse_dirt: Item
podzol: Item
rooted_dirt: Item
mud: Item
crimson_nylium: Item
warped_nylium: Item
cobblestone: Item
oak_planks: Item
spruce_planks: Item
birch_planks: Item
jungle_planks: Item
acacia_planks: Item
dark_oak_planks: Item
mangrove_planks: Item
crimson_planks: Item
warped_planks: Item
oak_sapling: Item
spruce_sapling: Item
birch_sapling: Item
jungle_sapling: Item
acacia_sapling: Item
dark_oak_sapling: Item
mangrove_propagule: Item
sand: Item
red_sand: Item
gravel: Item
coal_ore: Item
deepslate_coal_ore: Item
iron_ore: Item
deepslate_iron_ore: Item
copper_ore: Item
deepslate_copper_ore: Item
gold_ore: Item
deepslate_gold_ore: Item
redstone_ore: Item
deepslate_redstone_ore: Item
emerald_ore: Item
deepslate_emerald_ore: Item
lapis_ore: Item
deepslate_lapis_ore: Item
diamond_ore: Item
deepslate_diamond_ore: Item
nether_gold_ore: Item
nether_quartz_ore: Item
ancient_debris: Item
coal_block: Item
raw_iron_block: Item
raw_copper_block: Item
raw_gold_block: Item
amethyst_block: Item
iron_block: Item
copper_block: Item
gold_block: Item
diamond_block: Item
netherite_block: Item
exposed_copper: Item
weathered_copper: Item
oxidized_copper: Item
cut_copper: Item
exposed_cut_copper: Item
weathered_cut_copper: Item
oxidized_cut_copper: Item
cut_copper_stairs: Item
exposed_cut_copper_stairs: Item
weathered_cut_copper_stairs: Item
oxidized_cut_copper_stairs: Item
cut_copper_slab: Item
exposed_cut_copper_slab: Item
weathered_cut_copper_slab: Item
oxidized_cut_copper_slab: Item
waxed_copper_block: Item
waxed_exposed_copper: Item
waxed_weathered_copper: Item
waxed_oxidized_copper: Item
waxed_cut_copper: Item
waxed_exposed_cut_copper: Item
waxed_weathered_cut_copper: Item
waxed_oxidized_cut_copper: Item
waxed_cut_copper_stairs: Item
waxed_exposed_cut_copper_stairs: Item
waxed_weathered_cut_copper_stairs: Item
waxed_oxidized_cut_copper_stairs: Item
waxed_cut_copper_slab: Item
waxed_exposed_cut_copper_slab: Item
waxed_weathered_cut_copper_slab: Item
waxed_oxidized_cut_copper_slab: Item
oak_log: Item
spruce_log: Item
birch_log: Item
jungle_log: Item
acacia_log: Item
dark_oak_log: Item
mangrove_log: Item
mangrove_roots: Item
muddy_mangrove_roots: Item
crimson_stem: Item
warped_stem: Item
stripped_oak_log: Item
stripped_spruce_log: Item
stripped_birch_log: Item
stripped_jungle_log: Item
stripped_acacia_log: Item
stripped_dark_oak_log: Item
stripped_mangrove_log: Item
stripped_crimson_stem: Item
stripped_warped_stem: Item
stripped_oak_wood: Item
stripped_spruce_wood: Item
stripped_birch_wood: Item
stripped_jungle_wood: Item
stripped_acacia_wood: Item
stripped_dark_oak_wood: Item
stripped_mangrove_wood: Item
stripped_crimson_hyphae: Item
stripped_warped_hyphae: Item
oak_wood: Item
spruce_wood: Item
birch_wood: Item
jungle_wood: Item
acacia_wood: Item
dark_oak_wood: Item
mangrove_wood: Item
crimson_hyphae: Item
warped_hyphae: Item
oak_leaves: Item
spruce_leaves: Item
birch_leaves: Item
jungle_leaves: Item
acacia_leaves: Item
dark_oak_leaves: Item
mangrove_leaves: Item
azalea_leaves: Item
flowering_azalea_leaves: Item
sponge: Item
wet_sponge: Item
glass: Item
tinted_glass: Item
lapis_block: Item
sandstone: Item
chiseled_sandstone: Item
cut_sandstone: Item
cobweb: Item
grass: Item
fern: Item
azalea: Item
flowering_azalea: Item
dead_bush: Item
seagrass: Item
sea_pickle: Item
white_wool: Item
orange_wool: Item
magenta_wool: Item
light_blue_wool: Item
yellow_wool: Item
lime_wool: Item
pink_wool: Item
gray_wool: Item
light_gray_wool: Item
cyan_wool: Item
purple_wool: Item
blue_wool: Item
brown_wool: Item
green_wool: Item
red_wool: Item
black_wool: Item
dandelion: Item
poppy: Item
blue_orchid: Item
allium: Item
azure_bluet: Item
red_tulip: Item
orange_tulip: Item
white_tulip: Item
pink_tulip: Item
oxeye_daisy: Item
cornflower: Item
lily_of_the_valley: Item
wither_rose: Item
spore_blossom: Item
brown_mushroom: Item
red_mushroom: Item
crimson_fungus: Item
warped_fungus: Item
crimson_roots: Item
warped_roots: Item
nether_sprouts: Item
weeping_vines: Item
twisting_vines: Item
sugar_cane: Item
kelp: Item
moss_carpet: Item
moss_block: Item
hanging_roots: Item
big_dripleaf: Item
small_dripleaf: Item
bamboo: Item
oak_slab: Item
spruce_slab: Item
birch_slab: Item
jungle_slab: Item
acacia_slab: Item
dark_oak_slab: Item
mangrove_slab: Item
crimson_slab: Item
warped_slab: Item
stone_slab: Item
smooth_stone_slab: Item
sandstone_slab: Item
cut_sandstone_slab: Item
cobblestone_slab: Item
brick_slab: Item
stone_brick_slab: Item
mud_brick_slab: Item
nether_brick_slab: Item
quartz_slab: Item
red_sandstone_slab: Item
cut_red_sandstone_slab: Item
purpur_slab: Item
prismarine_slab: Item
prismarine_brick_slab: Item
dark_prismarine_slab: Item
smooth_quartz: Item
smooth_red_sandstone: Item
smooth_sandstone: Item
smooth_stone: Item
bricks: Item
bookshelf: Item
mossy_cobblestone: Item
obsidian: Item
torch: Item
end_rod: Item
chorus_flower: Item
purpur_block: Item
purpur_pillar: Item
purpur_stairs: Item
chest: Item
crafting_table: Item
furnace: Item
ladder: Item
cobblestone_stairs: Item
snow: Item
ice: Item
snow_block: Item
cactus: Item
clay: Item
jukebox: Item
oak_fence: Item
spruce_fence: Item
birch_fence: Item
jungle_fence: Item
acacia_fence: Item
dark_oak_fence: Item
mangrove_fence: Item
crimson_fence: Item
warped_fence: Item
pumpkin: Item
carved_pumpkin: Item
jack_o_lantern: Item
netherrack: Item
soul_sand: Item
soul_soil: Item
basalt: Item
polished_basalt: Item
smooth_basalt: Item
soul_torch: Item
glowstone: Item
stone_bricks: Item
mossy_stone_bricks: Item
cracked_stone_bricks: Item
chiseled_stone_bricks: Item
packed_mud: Item
mud_bricks: Item
deepslate_bricks: Item
cracked_deepslate_bricks: Item
deepslate_tiles: Item
cracked_deepslate_tiles: Item
chiseled_deepslate: Item
brown_mushroom_block: Item
red_mushroom_block: Item
mushroom_stem: Item
iron_bars: Item
chain: Item
glass_pane: Item
melon: Item
vine: Item
glow_lichen: Item
brick_stairs: Item
stone_brick_stairs: Item
mud_brick_stairs: Item
mycelium: Item
lily_pad: Item
nether_bricks: Item
cracked_nether_bricks: Item
chiseled_nether_bricks: Item
nether_brick_fence: Item
nether_brick_stairs: Item
sculk: Item
sculk_vein: Item
sculk_catalyst: Item
sculk_shrieker: Item
enchanting_table: Item
end_stone: Item
end_stone_bricks: Item
dragon_egg: Item
sandstone_stairs: Item
ender_chest: Item
emerald_block: Item
oak_stairs: Item
spruce_stairs: Item
birch_stairs: Item
jungle_stairs: Item
acacia_stairs: Item
dark_oak_stairs: Item
mangrove_stairs: Item
crimson_stairs: Item
warped_stairs: Item
beacon: Item
cobblestone_wall: Item
mossy_cobblestone_wall: Item
brick_wall: Item
prismarine_wall: Item
red_sandstone_wall: Item
mossy_stone_brick_wall: Item
granite_wall: Item
stone_brick_wall: Item
mud_brick_wall: Item
nether_brick_wall: Item
andesite_wall: Item
red_nether_brick_wall: Item
sandstone_wall: Item
end_stone_brick_wall: Item
diorite_wall: Item
blackstone_wall: Item
polished_blackstone_wall: Item
polished_blackstone_brick_wall: Item
cobbled_deepslate_wall: Item
polished_deepslate_wall: Item
deepslate_brick_wall: Item
deepslate_tile_wall: Item
anvil: Item
chipped_anvil: Item
damaged_anvil: Item
chiseled_quartz_block: Item
quartz_block: Item
quartz_bricks: Item
quartz_pillar: Item
quartz_stairs: Item
white_terracotta: Item
orange_terracotta: Item
magenta_terracotta: Item
light_blue_terracotta: Item
yellow_terracotta: Item
lime_terracotta: Item
pink_terracotta: Item
gray_terracotta: Item
light_gray_terracotta: Item
cyan_terracotta: Item
purple_terracotta: Item
blue_terracotta: Item
brown_terracotta: Item
green_terracotta: Item
red_terracotta: Item
black_terracotta: Item
hay_block: Item
white_carpet: Item
orange_carpet: Item
magenta_carpet: Item
light_blue_carpet: Item
yellow_carpet: Item
lime_carpet: Item
pink_carpet: Item
gray_carpet: Item
light_gray_carpet: Item
cyan_carpet: Item
purple_carpet: Item
blue_carpet: Item
brown_carpet: Item
green_carpet: Item
red_carpet: Item
black_carpet: Item
terracotta: Item
packed_ice: Item
sunflower: Item
lilac: Item
rose_bush: Item
peony: Item
tall_grass: Item
large_fern: Item
white_stained_glass: Item
orange_stained_glass: Item
magenta_stained_glass: Item
light_blue_stained_glass: Item
yellow_stained_glass: Item
lime_stained_glass: Item
pink_stained_glass: Item
gray_stained_glass: Item
light_gray_stained_glass: Item
cyan_stained_glass: Item
purple_stained_glass: Item
blue_stained_glass: Item
brown_stained_glass: Item
green_stained_glass: Item
red_stained_glass: Item
black_stained_glass: Item
white_stained_glass_pane: Item
orange_stained_glass_pane: Item
magenta_stained_glass_pane: Item
light_blue_stained_glass_pane: Item
yellow_stained_glass_pane: Item
lime_stained_glass_pane: Item
pink_stained_glass_pane: Item
gray_stained_glass_pane: Item
light_gray_stained_glass_pane: Item
cyan_stained_glass_pane: Item
purple_stained_glass_pane: Item
blue_stained_glass_pane: Item
brown_stained_glass_pane: Item
green_stained_glass_pane: Item
red_stained_glass_pane: Item
black_stained_glass_pane: Item
prismarine: Item
prismarine_bricks: Item
dark_prismarine: Item
prismarine_stairs: Item
prismarine_brick_stairs: Item
dark_prismarine_stairs: Item
sea_lantern: Item
red_sandstone: Item
chiseled_red_sandstone: Item
cut_red_sandstone: Item
red_sandstone_stairs: Item
magma_block: Item
nether_wart_block: Item
warped_wart_block: Item
red_nether_bricks: Item
bone_block: Item
shulker_box: Item
white_shulker_box: Item
orange_shulker_box: Item
magenta_shulker_box: Item
light_blue_shulker_box: Item
yellow_shulker_box: Item
lime_shulker_box: Item
pink_shulker_box: Item
gray_shulker_box: Item
light_gray_shulker_box: Item
cyan_shulker_box: Item
purple_shulker_box: Item
blue_shulker_box: Item
brown_shulker_box: Item
green_shulker_box: Item
red_shulker_box: Item
black_shulker_box: Item
white_glazed_terracotta: Item
orange_glazed_terracotta: Item
magenta_glazed_terracotta: Item
light_blue_glazed_terracotta: Item
yellow_glazed_terracotta: Item
lime_glazed_terracotta: Item
pink_glazed_terracotta: Item
gray_glazed_terracotta: Item
light_gray_glazed_terracotta: Item
cyan_glazed_terracotta: Item
purple_glazed_terracotta: Item
blue_glazed_terracotta: Item
brown_glazed_terracotta: Item
green_glazed_terracotta: Item
red_glazed_terracotta: Item
black_glazed_terracotta: Item
white_concrete: Item
orange_concrete: Item
magenta_concrete: Item
light_blue_concrete: Item
yellow_concrete: Item
lime_concrete: Item
pink_concrete: Item
gray_concrete: Item
light_gray_concrete: Item
cyan_concrete: Item
purple_concrete: Item
blue_concrete: Item
brown_concrete: Item
green_concrete: Item
red_concrete: Item
black_concrete: Item
white_concrete_powder: Item
orange_concrete_powder: Item
magenta_concrete_powder: Item
light_blue_concrete_powder: Item
yellow_concrete_powder: Item
lime_concrete_powder: Item
pink_concrete_powder: Item
gray_concrete_powder: Item
light_gray_concrete_powder: Item
cyan_concrete_powder: Item
purple_concrete_powder: Item
blue_concrete_powder: Item
brown_concrete_powder: Item
green_concrete_powder: Item
red_concrete_powder: Item
black_concrete_powder: Item
turtle_egg: Item
dead_tube_coral_block: Item
dead_brain_coral_block: Item
dead_bubble_coral_block: Item
dead_fire_coral_block: Item
dead_horn_coral_block: Item
tube_coral_block: Item
brain_coral_block: Item
bubble_coral_block: Item
fire_coral_block: Item
horn_coral_block: Item
tube_coral: Item
brain_coral: Item
bubble_coral: Item
fire_coral: Item
horn_coral: Item
dead_brain_coral: Item
dead_bubble_coral: Item
dead_fire_coral: Item
dead_horn_coral: Item
dead_tube_coral: Item
tube_coral_fan: Item
brain_coral_fan: Item
bubble_coral_fan: Item
fire_coral_fan: Item
horn_coral_fan: Item
dead_tube_coral_fan: Item
dead_brain_coral_fan: Item
dead_bubble_coral_fan: Item
dead_fire_coral_fan: Item
dead_horn_coral_fan: Item
blue_ice: Item
conduit: Item
polished_granite_stairs: Item
smooth_red_sandstone_stairs: Item
mossy_stone_brick_stairs: Item
polished_diorite_stairs: Item
mossy_cobblestone_stairs: Item
end_stone_brick_stairs: Item
stone_stairs: Item
smooth_sandstone_stairs: Item
smooth_quartz_stairs: Item
granite_stairs: Item
andesite_stairs: Item
red_nether_brick_stairs: Item
polished_andesite_stairs: Item
diorite_stairs: Item
cobbled_deepslate_stairs: Item
polished_deepslate_stairs: Item
deepslate_brick_stairs: Item
deepslate_tile_stairs: Item
polished_granite_slab: Item
smooth_red_sandstone_slab: Item
mossy_stone_brick_slab: Item
polished_diorite_slab: Item
mossy_cobblestone_slab: Item
end_stone_brick_slab: Item
smooth_sandstone_slab: Item
smooth_quartz_slab: Item
granite_slab: Item
andesite_slab: Item
red_nether_brick_slab: Item
polished_andesite_slab: Item
diorite_slab: Item
cobbled_deepslate_slab: Item
polished_deepslate_slab: Item
deepslate_brick_slab: Item
deepslate_tile_slab: Item
scaffolding: Item
redstone: Item
redstone_torch: Item
redstone_block: Item
repeater: Item
comparator: Item
piston: Item
sticky_piston: Item
slime_block: Item
honey_block: Item
observer: Item
hopper: Item
dispenser: Item
dropper: Item
lectern: Item
target: Item
lever: Item
lightning_rod: Item
daylight_detector: Item
sculk_sensor: Item
tripwire_hook: Item
trapped_chest: Item
tnt: Item
redstone_lamp: Item
note_block: Item
stone_button: Item
polished_blackstone_button: Item
oak_button: Item
spruce_button: Item
birch_button: Item
jungle_button: Item
acacia_button: Item
dark_oak_button: Item
mangrove_button: Item
crimson_button: Item
warped_button: Item
stone_pressure_plate: Item
polished_blackstone_pressure_plate: Item
light_weighted_pressure_plate: Item
heavy_weighted_pressure_plate: Item
oak_pressure_plate: Item
spruce_pressure_plate: Item
birch_pressure_plate: Item
jungle_pressure_plate: Item
acacia_pressure_plate: Item
dark_oak_pressure_plate: Item
mangrove_pressure_plate: Item
crimson_pressure_plate: Item
warped_pressure_plate: Item
iron_door: Item
oak_door: Item
spruce_door: Item
birch_door: Item
jungle_door: Item
acacia_door: Item
dark_oak_door: Item
mangrove_door: Item
crimson_door: Item
warped_door: Item
iron_trapdoor: Item
oak_trapdoor: Item
spruce_trapdoor: Item
birch_trapdoor: Item
jungle_trapdoor: Item
acacia_trapdoor: Item
dark_oak_trapdoor: Item
mangrove_trapdoor: Item
crimson_trapdoor: Item
warped_trapdoor: Item
oak_fence_gate: Item
spruce_fence_gate: Item
birch_fence_gate: Item
jungle_fence_gate: Item
acacia_fence_gate: Item
dark_oak_fence_gate: Item
mangrove_fence_gate: Item
crimson_fence_gate: Item
warped_fence_gate: Item
powered_rail: Item
detector_rail: Item
rail: Item
activator_rail: Item
saddle: Item
minecart: Item
chest_minecart: Item
furnace_minecart: Item
tnt_minecart: Item
hopper_minecart: Item
carrot_on_a_stick: Item
warped_fungus_on_a_stick: Item
elytra: Item
oak_boat: Item
oak_chest_boat: Item
spruce_boat: Item
spruce_chest_boat: Item
birch_boat: Item
birch_chest_boat: Item
jungle_boat: Item
jungle_chest_boat: Item
acacia_boat: Item
acacia_chest_boat: Item
dark_oak_boat: Item
dark_oak_chest_boat: Item
mangrove_boat: Item
mangrove_chest_boat: Item
turtle_helmet: Item
scute: Item
flint_and_steel: Item
apple: Item
bow: Item
arrow: Item
coal: Item
charcoal: Item
diamond: Item
emerald: Item
lapis_lazuli: Item
quartz: Item
amethyst_shard: Item
raw_iron: Item
iron_ingot: Item
raw_copper: Item
copper_ingot: Item
raw_gold: Item
gold_ingot: Item
netherite_ingot: Item
netherite_scrap: Item
wooden_sword: Item
wooden_shovel: Item
wooden_pickaxe: Item
wooden_axe: Item
wooden_hoe: Item
stone_sword: Item
stone_shovel: Item
stone_pickaxe: Item
stone_axe: Item
stone_hoe: Item
golden_sword: Item
golden_shovel: Item
golden_pickaxe: Item
golden_axe: Item
golden_hoe: Item
iron_sword: Item
iron_shovel: Item
iron_pickaxe: Item
iron_axe: Item
iron_hoe: Item
diamond_sword: Item
diamond_shovel: Item
diamond_pickaxe: Item
diamond_axe: Item
diamond_hoe: Item
netherite_sword: Item
netherite_shovel: Item
netherite_pickaxe: Item
netherite_axe: Item
netherite_hoe: Item
stick: Item
bowl: Item
mushroom_stew: Item
string: Item
feather: Item
gunpowder: Item
wheat_seeds: Item
wheat: Item
bread: Item
leather_helmet: Item
leather_chestplate: Item
leather_leggings: Item
leather_boots: Item
chainmail_helmet: Item
chainmail_chestplate: Item
chainmail_leggings: Item
chainmail_boots: Item
iron_helmet: Item
iron_chestplate: Item
iron_leggings: Item
iron_boots: Item
diamond_helmet: Item
diamond_chestplate: Item
diamond_leggings: Item
diamond_boots: Item
golden_helmet: Item
golden_chestplate: Item
golden_leggings: Item
golden_boots: Item
netherite_helmet: Item
netherite_chestplate: Item
netherite_leggings: Item
netherite_boots: Item
flint: Item
porkchop: Item
cooked_porkchop: Item
painting: Item
golden_apple: Item
enchanted_golden_apple: Item
oak_sign: Item
spruce_sign: Item
birch_sign: Item
jungle_sign: Item
acacia_sign: Item
dark_oak_sign: Item
mangrove_sign: Item
crimson_sign: Item
warped_sign: Item
bucket: Item
water_bucket: Item
lava_bucket: Item
powder_snow_bucket: Item
snowball: Item
leather: Item
milk_bucket: Item
pufferfish_bucket: Item
salmon_bucket: Item
cod_bucket: Item
tropical_fish_bucket: Item
axolotl_bucket: Item
tadpole_bucket: Item
brick: Item
clay_ball: Item
dried_kelp_block: Item
paper: Item
book: Item
slime_ball: Item
egg: Item
compass: Item
recovery_compass: Item
fishing_rod: Item
clock: Item
spyglass: Item
glowstone_dust: Item
cod: Item
salmon: Item
tropical_fish: Item
pufferfish: Item
cooked_cod: Item
cooked_salmon: Item
ink_sac: Item
glow_ink_sac: Item
cocoa_beans: Item
white_dye: Item
orange_dye: Item
magenta_dye: Item
light_blue_dye: Item
yellow_dye: Item
lime_dye: Item
pink_dye: Item
gray_dye: Item
light_gray_dye: Item
cyan_dye: Item
purple_dye: Item
blue_dye: Item
brown_dye: Item
green_dye: Item
red_dye: Item
black_dye: Item
bone_meal: Item
bone: Item
sugar: Item
cake: Item
white_bed: Item
orange_bed: Item
magenta_bed: Item
light_blue_bed: Item
yellow_bed: Item
lime_bed: Item
pink_bed: Item
gray_bed: Item
light_gray_bed: Item
cyan_bed: Item
purple_bed: Item
blue_bed: Item
brown_bed: Item
green_bed: Item
red_bed: Item
black_bed: Item
cookie: Item
filled_map: Item
shears: Item
melon_slice: Item
dried_kelp: Item
pumpkin_seeds: Item
melon_seeds: Item
beef: Item
cooked_beef: Item
chicken: Item
cooked_chicken: Item
rotten_flesh: Item
ender_pearl: Item
blaze_rod: Item
ghast_tear: Item
gold_nugget: Item
nether_wart: Item
potion: Item
glass_bottle: Item
spider_eye: Item
fermented_spider_eye: Item
blaze_powder: Item
magma_cream: Item
brewing_stand: Item
cauldron: Item
ender_eye: Item
glistering_melon_slice: Item
experience_bottle: Item
fire_charge: Item
writable_book: Item
written_book: Item
item_frame: Item
glow_item_frame: Item
flower_pot: Item
carrot: Item
potato: Item
baked_potato: Item
poisonous_potato: Item
map: Item
golden_carrot: Item
skeleton_skull: Item
wither_skeleton_skull: Item
zombie_head: Item
creeper_head: Item
dragon_head: Item
nether_star: Item
pumpkin_pie: Item
firework_rocket: Item
firework_star: Item
enchanted_book: Item
nether_brick: Item
prismarine_shard: Item
prismarine_crystals: Item
rabbit: Item
cooked_rabbit: Item
rabbit_stew: Item
rabbit_foot: Item
rabbit_hide: Item
armor_stand: Item
iron_horse_armor: Item
golden_horse_armor: Item
diamond_horse_armor: Item
leather_horse_armor: Item
lead: Item
name_tag: Item
mutton: Item
cooked_mutton: Item
white_banner: Item
orange_banner: Item
magenta_banner: Item
light_blue_banner: Item
yellow_banner: Item
lime_banner: Item
pink_banner: Item
gray_banner: Item
light_gray_banner: Item
cyan_banner: Item
purple_banner: Item
blue_banner: Item
brown_banner: Item
green_banner: Item
red_banner: Item
black_banner: Item
end_crystal: Item
chorus_fruit: Item
popped_chorus_fruit: Item
beetroot: Item
beetroot_seeds: Item
beetroot_soup: Item
dragon_breath: Item
splash_potion: Item
spectral_arrow: Item
tipped_arrow: Item
lingering_potion: Item
shield: Item
totem_of_undying: Item
shulker_shell: Item
iron_nugget: Item
music_disc_13: Item
music_disc_cat: Item
music_disc_blocks: Item
music_disc_chirp: Item
music_disc_far: Item
music_disc_mall: Item
music_disc_mellohi: Item
music_disc_stal: Item
music_disc_strad: Item
music_disc_ward: Item
music_disc_11: Item
music_disc_wait: Item
music_disc_otherside: Item
music_disc_pigstep: Item
trident: Item
phantom_membrane: Item
nautilus_shell: Item
heart_of_the_sea: Item
crossbow: Item
suspicious_stew: Item
loom: Item
flower_banner_pattern: Item
creeper_banner_pattern: Item
skull_banner_pattern: Item
mojang_banner_pattern: Item
globe_banner_pattern: Item
piglin_banner_pattern: Item
composter: Item
barrel: Item
smoker: Item
blast_furnace: Item
cartography_table: Item
fletching_table: Item
grindstone: Item
smithing_table: Item
stonecutter: Item
bell: Item
lantern: Item
soul_lantern: Item
sweet_berries: Item
glow_berries: Item
campfire: Item
soul_campfire: Item
shroomlight: Item
honeycomb: Item
bee_nest: Item
beehive: Item
honey_bottle: Item
honeycomb_block: Item
lodestone: Item
crying_obsidian: Item
blackstone: Item
blackstone_slab: Item
blackstone_stairs: Item
gilded_blackstone: Item
polished_blackstone: Item
polished_blackstone_slab: Item
polished_blackstone_stairs: Item
chiseled_polished_blackstone: Item
polished_blackstone_bricks: Item
polished_blackstone_brick_slab: Item
polished_blackstone_brick_stairs: Item
cracked_polished_blackstone_bricks: Item
respawn_anchor: Item
candle: Item
white_candle: Item
orange_candle: Item
magenta_candle: Item
light_blue_candle: Item
yellow_candle: Item
lime_candle: Item
pink_candle: Item
gray_candle: Item
light_gray_candle: Item
cyan_candle: Item
purple_candle: Item
blue_candle: Item
brown_candle: Item
green_candle: Item
red_candle: Item
black_candle: Item
small_amethyst_bud: Item
medium_amethyst_bud: Item
large_amethyst_bud: Item
amethyst_cluster: Item
pointed_dripstone: Item
ochre_froglight: Item
verdant_froglight: Item
pearlescent_froglight: Item
echo_shard: Item
bedrock: Item
budding_amethyst: Item
petrified_oak_slab: Item
chorus_plant: Item
spawner: Item
farmland: Item
infested_stone: Item
infested_cobblestone: Item
infested_stone_bricks: Item
infested_mossy_stone_bricks: Item
infested_cracked_stone_bricks: Item
infested_chiseled_stone_bricks: Item
infested_deepslate: Item
reinforced_deepslate: Item
end_portal_frame: Item
command_block: Item
barrier: Item
light: Item
dirt_path: Item
repeating_command_block: Item
chain_command_block: Item
structure_void: Item
structure_block: Item
jigsaw: Item
bundle: Item
allay_spawn_egg: Item
axolotl_spawn_egg: Item
bat_spawn_egg: Item
bee_spawn_egg: Item
blaze_spawn_egg: Item
cat_spawn_egg: Item
cave_spider_spawn_egg: Item
chicken_spawn_egg: Item
cod_spawn_egg: Item
cow_spawn_egg: Item
creeper_spawn_egg: Item
dolphin_spawn_egg: Item
donkey_spawn_egg: Item
drowned_spawn_egg: Item
elder_guardian_spawn_egg: Item
enderman_spawn_egg: Item
endermite_spawn_egg: Item
evoker_spawn_egg: Item
fox_spawn_egg: Item
frog_spawn_egg: Item
ghast_spawn_egg: Item
glow_squid_spawn_egg: Item
goat_spawn_egg: Item
guardian_spawn_egg: Item
hoglin_spawn_egg: Item
horse_spawn_egg: Item
husk_spawn_egg: Item
llama_spawn_egg: Item
magma_cube_spawn_egg: Item
mooshroom_spawn_egg: Item
mule_spawn_egg: Item
ocelot_spawn_egg: Item
panda_spawn_egg: Item
parrot_spawn_egg: Item
phantom_spawn_egg: Item
pig_spawn_egg: Item
piglin_spawn_egg: Item
piglin_brute_spawn_egg: Item
pillager_spawn_egg: Item
polar_bear_spawn_egg: Item
pufferfish_spawn_egg: Item
rabbit_spawn_egg: Item
ravager_spawn_egg: Item
salmon_spawn_egg: Item
sheep_spawn_egg: Item
shulker_spawn_egg: Item
silverfish_spawn_egg: Item
skeleton_spawn_egg: Item
skeleton_horse_spawn_egg: Item
slime_spawn_egg: Item
spider_spawn_egg: Item
squid_spawn_egg: Item
stray_spawn_egg: Item
strider_spawn_egg: Item
tadpole_spawn_egg: Item
trader_llama_spawn_egg: Item
tropical_fish_spawn_egg: Item
turtle_spawn_egg: Item
vex_spawn_egg: Item
villager_spawn_egg: Item
vindicator_spawn_egg: Item
wandering_trader_spawn_egg: Item
warden_spawn_egg: Item
witch_spawn_egg: Item
wither_skeleton_spawn_egg: Item
wolf_spawn_egg: Item
zoglin_spawn_egg: Item
zombie_spawn_egg: Item
zombie_horse_spawn_egg: Item
zombie_villager_spawn_egg: Item
zombified_piglin_spawn_egg: Item
player_head: Item
command_block_minecart: Item
knowledge_book: Item
debug_stick: Item
frogspawn: Item